- README.md
- boot.js
- test/after-and-ready.js
It adds `after()` and `ready()` calls to add more things into the loading queue.
cc @mcdonnelldean
> after() and ready()

- README.md
- boot.js
- example.js
- package.json
- test/chainable.js
- test/express.js
@mcdonnelldean @lucamaraschi please review this. It should provide what we need.
Fixes #2
> Chainable API

- README.md
- boot.js
- test/use-array.js
> Added support for an array of plugins in boot.use

- boot.js
- package.json
- test/basic.js
> Fix deferred ready

- boot.js
- test/close.js
> Handle missing callback when calling close

- plugin.js
- test/basic.js
Fixes https://github.com/fastify/fastify-mongodb/issues/8.
> Defer nested "use" calls to the nextTick

- README.md
- boot.js
- test/after-and-ready.test.js
As titled.
Related: https://github.com/fastify/fastify/pull/454 https://github.com/fastify/fastify/issues/460
> After should passthrough the errors

- boot.js
- package.json
- test/basic.test.js
- test/close.test.js
It also add a promise option for close
> Fixes after 4.0.0 release

- README.md
- boot.js
- package.json
- plugin.js
- test/after-and-ready.test.js
- test/callbacks.test.js
- test/use-array.test.js
As titled.
This change will need a new major release.
Related: https://github.com/fastify/fastify/issues/460
> Removed callback from use

- package.json
- plugin.js
- test/after-throw.test.js
Fixes https://github.com/fastify/fastify/issues/755
cc @delvedor
> Escape the promise context to avoid a try/catch

- README.md
- boot.js
- plugin.js
- test/after-and-ready.test.js
- test/basic.test.js
Fixes https://github.com/mcollina/avvio/pull/45
Fixes https://github.com/fastify/fastify/issues/757
cc @fastify @allevo
> fail fast until an after is found

- README.md
- boot.js
- test/after-and-ready.test.js
> preReady event

- README.md
- boot.js
- test/basic.test.js
As titled and referenced in #50.
> Return `this` from `.start()`

- .travis.yml
- boot.js
- test/events-listeners.test.js
As titled, also updated travis.
Fixes https://github.com/fastify/fastify/issues/791.
> Increased max listeners

- README.md
Or at least made it less violent.
> Fix typo in `README.md`.

- README.md
- boot.js
- example.js
- plugin.js
- test/fixtures/plugin-no-next.js
- test/plugin-timeout.js
This would help solving one of the major pain points of using Fastify, developers not calling their callback and having trouble to debug where the the loading process have stopped.
> Plugin timeout

- boot.js
- test/basic.test.js
Ref to:
https://github.com/fastify/fastify/pull/2077
> add preready managing errors

- boot.js
- plugin.js
- test/await-after.test.js
- test/basic.test.js
This PR simplifies the asyncq logic.
> No async q - use a Promise instead

- boot.js
- test/after-and-ready.test.js
Fixes: https://github.com/fastify/fastify/issues/2194
> Allow after to swallow/handle errors

- plugin.js
- test/after-self-promise.js
Fixes https://github.com/fastify/fastify-express/pull/2
> Support returning an instance of server in after(cb)

- boot.js
- test/after-and-ready.test.js
Backport of #115 
Fastify v2 runs avvio v6
> ready:Promise should return the server instance

- .github/workflows/ci.yml
- README.md
- boot.js
- package.json
- plugin.js
- test/basic.test.js
- test/close.test.js
- test/events-listeners.test.js
- test/override.test.js
Hope it's okay for me to collect up these sort of tidying pull requests into a single one rather than multiple pull requests for docs/ci/linting etc.
> chore: lint code; documentation fixes

- .github/workflows/ci.yml
- .taprc
- package.json
- test/after-and-ready.test.js
- test/after-pass-through.test.js
- test/async-await.test.js
- test/await-after.test.js
- test/await-self.test.js
- test/await-use.test.js
- test/basic.test.js
- test/callbacks.test.js
- test/close.test.js
- test/esm.mjs
- test/express.test.js
- test/override.test.js
- test/plugin-timeout.test.js
- test/pretty-print.test.js
- test/to-json.test.js
> Update to tap@15

- .github/workflows/ci.yml
- package.json
> ci: add automerge job

- test/after-and-ready.test.js
- test/after-pass-through.test.js
- test/after-throw.test.js
- test/async-await.test.js
- test/basic.test.js
- test/callbacks.test.js
- test/catch-override-exception.test.js
- test/chainable.test.js
- test/close.test.js
- test/errors.test.js
- test/esm.mjs
- test/esm.test.js
- test/events-listeners.test.js
- test/express.test.js
- test/override.test.js
- test/plugin-name.test.js
- test/plugin-timeout.test.js
- test/pretty-print.test.js
- test/reentrant.test.js
- test/to-json.test.js
- test/twice-done.test.js
- change test case for `esm.test.js`
- beauty test cases
> test: add test description &  change test require style & change case  for esm test

- README.md
See https://github.com/fastify/fastify/pull/3875
> docs: use npm `install` alias; remove redundant `--save` arg

- boot.js
- lib/debug.js
- package.json
- plugin.js
> replace debug with node built-in

- .github/workflows/ci.yml
- .taprc
- package.json
It is a little bit annoying to fix linting errors manually ;)
> add lint and lint:fix npm scripts and also split up npm script test

- lib/debug.js
> chore: jsdoc for debug

- examples/example.js
> chore: move example into examples folder

- boot.js
> chore: simplify callback

- boot.js
introduced accidently a merge error in #237 
> fix: merge error

- README.md
> Documentation: Fixed broken link in `README.md`

- .github/workflows/ci.yml
`node-versions` can be passed as an argument as observed here:
https://github.com/fastify/workflows/blob/main/.github/workflows/plugins-ci.yml#L34
> ci: updates to run with node 22

- test/events-listeners.test.js
See https://github.com/fastify/fastify/issues/5756
> test(events-listeners): replace `var` with `let`
