README.md
boot.js
test/override.js

Added app.override() to create plugin inheritance chain

---

README.md
boot.js
test/override.js

In the previous PR (#9) we added the ovverride support to create a plugin inheritance chain.
Sometimes, for some reason, the user needs to disable the override if he has set one.
With this PR we support that.
Example:
```js
const server = { my: 'server' }
const app = boot(server)
app.override = function (s) {
return Object.create(s)
}
first[Symbol.for('skip-override')] = true
app.use(first)
function first (s, opts, cb) {
// some code
cb()
}
```
If this is 👍  for you, I can proceed to update the docs.

Skip override

---

README.md
boot.js
test/after-and-ready.js
test/override.js

- `override` takes as second parameter the plugin function
- if `after`/`ready` have two parameters, the first one is the context (this to avoid breaking changes) #6

Updated override and after/ready callbacks

---

README.md
boot.js
test/override.js

Sometimes can be useful pass some options to the `override` function, this PR enables that :)

Pass options object to override function

---

.travis.yml
README.md
boot.js
package.json
plugin.js
test/basic.js
test/close.js

With this PR we introduce a new queue to handle the shutdown procedure, following the *avvio* style!
- Use `onClose` to add new functions to execute.
- Use `close` to start the process
Related: https://github.com/fastify/fastify/issues/123
Feedbacks?

Close queue

---

boot.js
test/after-and-ready.js

Do not erase error if callback is called sync

---

boot.js
test/close.js

Expose the error only inside the close callback

---

.gitignore
README.md
boot.js
test/after-and-ready.js
test/close.js

We are not passing the correct encapsulated instance when using `override`, this pr aims to fix that.

Updated encapsulation handling

---

README.md

The `boot` variable was still in use since the module got renamed and caused confusion for some people. This change makes the documentation a bit more readable.
There's still https://github.com/mcollina/avvio/issues/24 to tackle.

Replace legacy `boot` variable with the `app` avvioo instance

---

boot.js
package.json
test/close.test.js

If calling `.close()` with a non-function, throw.

close must receive a function or a falsey value

---

README.md
boot.js
test/basic.test.js

This should solve https://github.com/fastify/fastify/issues/491
cc @jsumners

Added an autostart flag to defer loading

---

plugin.js
test/catch-override-exception.test.js

This PR should allow https://github.com/fastify/fastify/pull/778 to be fixed.
N.B.: I think `Boot.prototype.start` should return `this`. Do you?

Catch exceptions in parent.override

---

boot.js
test/close.test.js

This fixes two bugs:
1. `await fastify.close()` actually waits for close to happen
2. stop errors from bubbling up if they happen when closing (they will end up in the rejection handler).
cc @StarpTech @allevo

wrapped close should return a promise with no callback

---

index.d.ts

This pull request allows to improve the overload of typecript definitions when the expose option is changed by creating an interface for ready, use and after. I would publish an example in commentary of this PR.
Thanks ^^

Modularization of Avvio's methods

---

index.d.ts
test/types/index.ts

I realized that I had forgotten the interfaces for onClose and close properties on the wrapped instance. Added

Add onClose and close in TS definitions

---

boot.js
test/after-pass-through.test.js
test/async-await.js

Unfortunately `after(async function () {})` did not work properly when wrapping like in Fastify.
Includes #74 as well.

 Proper support for after with a passed async function in wrapped mode

---

README.md
test/twice-done.test.js

Add test to verify lack of exception from calling done twice.
Fixes #39

Fix documentation for multiple calls to `done`.

---

boot.js
test/close.test.js

Attempting https://github.com/fastify/fastify/issues/629
Not sure if this is the right thing to do but based on `encapsulateThreeParam` I came up with this solution.

Support on close without the instance object

---

README.md
package.json
plugin.js
test/basic.test.js

Attempting [fastify/fastify#1489](https://github.com/fastify/fastify/issues/1489)
An external dependency `fast-deepclone` was added as `Object.assign({}, variable)` wouldn't suit our purpose due to it being a shallow copy and thus passing by reference. The operational overhead is minimal thanks to the module being coded natively in C++. Its license is [MIT](https://github.com/scottinet/fast-deepclone/blob/master/LICENSE) which I believe is compatibly with this project's license.
Added unit tests as well. Let me know your thoughts.

Added support for a function in place of opts

---

README.md
plugin.js
test/basic.test.js
test/override.test.js

Hello again,
It appears the original PR I had made was passing in the wrong variable to the function that was passed in as `options`. In this PR, I have updated the previous test case and added a new one for `override`. 
In short, instead of binding the `parent` instance of the plugin during declaration and evaluating it during execution, we directly evaluate the function during execution after the `override` function has been called by passing `this.server` to it as an argument. This should provide more consistent and expected results from the change.
Also added slight documentation change to showcase the default behavior.
Let me know your thoughts.
Kind regards,
Alex P.

Fixed function as option variable reference issue of PR82

---

boot.js
example.js
test/after-use-after.test.js

This revert a bit done what was done in https://github.com/mcollina/avvio/pull/81 by @Eomm. We have to report the `after` calls to the time tracker, otherwise we lose the trace of what we have loaded. However, this pollutes the `.toJSON()` and pretty-print representation of this.
I think we should land this as patch asap, and then find out what to do with the pretty print.
Fixes: https://github.com/fastify/fastify/issues/1781

Do not crash within after when registering a plugin

---

test/pretty-print.test.js

Since the test wasn't failing due #88, I would add the `after` call in the pretty tests.
This is the output:
```
bound root 195 ms
├── first 0 ms
├─┬ duplicate 86 ms
│ └─┬ duplicate 64 ms
│   └─┬ duplicate 42 ms
│     └── duplicate 21 ms
├── second 0 ms
├─┬ bound _after 0 ms
│ └── afterInsider 0 ms
├── bound _after 0 ms
├─┬ duplicate 63 ms
│ └─┬ duplicate 41 ms
│   └── duplicate 21 ms
├── third 0 ms
├── bound _after 0 ms
└─┬ duplicate 41 ms
└── duplicate 21 ms
```
that is not good for fastify because there is always a `bound _after` entry for each `register` call.
I will try to fix this behaviour in separate PR

fix test pretty print after

---

.travis.yml
README.md
boot.js
package.json
plugin.js
test/async-await.js
test/chainable.test.js
test/esm.mjs
test/esm.test.js
test/fixtures/esm.mjs
test/override.test.js
test/pretty-print.test.js

The goal of this PR is to add support for `import()` statements for plugins. In this way, if we want to load an ESM, Node could potentially load all of them in parallel while we process one at a time.
In fastify lingo:
```js
app.register(import('path/to/plugin'), opts)
```
The way this is implemented in this PR is to add support for promises: import() returns a promise.
This needs:

Basic support for promise plugins / esm with import

---

boot.js
plugin.js
test/after-and-ready.test.js
test/await-after.test.js

This PR changes substantially how our `await app.register()` and `await app.after()` works. Essentially, it's impossible to "skip error and continue", as we were doing before. Instead, this makes the promise reject.
Fixes #93 
Fixes #94

Await fixes

---

plugin.js
test/after-pass-through.test.js
test/await-after.test.js
test/await-use.test.js

In #95, I _thought_ I did this. Turns out I was missing a critical change, this is it.

Actually rejects when await app.after() or await app.register()

---

README.md
boot.js
plugin.js
test/await-after.test.js
test/override.test.js

I lied 😅
My snippet didn't check the all the after's functions were wrapped in a function that had always 3 params.
Now the flow that calls `.after()` without any parameter doesn't work.. still working on it
Fixes #101

After override

---

boot.js
test/plugin-timeout.test.js

fix timeout on ready (master)

---

boot.js
test/close.test.js

While fixing fastify/fastify#2250 I noticed that the onClose handler with one parameter mistakenly gets the `done` as the only argument, while the documentation says it should get the `context` instead. 
This PR fixes the issue.

Correctly handle async onClose with one  parameter

---

plugin.js
test/override.test.js

Fixes https://github.com/fastify/fastify/issues/2406

Registering plugins inside after should trigger override

---

boot.js
test/after-and-ready.test.js

The `ready()` interface return a `Promise<server>` that return always the root server.
I have added the tests:
- with callback style all is fine
- with promise style, the issue shows
Blocking this PR https://github.com/fastify/fastify/pull/2361

ready:Promise should return the server instance

---

boot.js
test/basic.test.js

This is one of those changes that I would prefer not to put in. However I think it would improve the development experience for TypeScript and babel users that have problem with "faux modules" (esm syntax transplied to cjs).
I think it can help resolving https://github.com/fastify/fastify/issues/2404.

Support faux modules

---

boot.js
plugin.js
test/plugin-timeout.test.js

Just because this has happened to me many times :-) 

Better error message for ERR_AVVIO_PLUGIN_TIMEOUT

---

index.d.ts
test/types/index.ts

- `npm run benchmark` fails with `missing script: benchmark`
- not relevant
- not relevant
Btw, the test fails with an `listen EADDRINUSE: address already in use :::3000` if there is something else listening on port `3000` where the tests is run.

fix typescript declaration for app.use with async functions

---

boot.js
lib/errors.js
plugin.js
test/callbacks.test.js
test/chainable.test.js
test/errors.test.js
test/plugin-timeout.test.js

Implements [Fastify#2842](https://github.com/fastify/fastify/issues/2842)

feat: implement error factory

---

plugin.js
test/fixtures/plugin-no-next.js
test/plugin-name.test.js
test/plugin-timeout.test.js

This is a second approach to the same thing in #140.
`getName` in avvio gets a string name for each plugin registered to use when reporting debug info. Doing some profiling of a big fastify application, I noticed that a lot of time was spent getting the name of avvio plugins in the `getName` function. For me, `require.cache` was very big, and the number of registered plugins was very big, so the O(n^2) search for each file in the require cache was actually taking a good long while. Also, `getName` relying on the require cache is undesirable as ESM becomes more and more common -- we should try to move to an approach that doesn't need that.
Fortunately, a lot of plugins registered with avvio already report their names! We were somewhat accidentally using `getName` to get the name of a lot …

Use fastify plugin metadata or an explicit passed in name option for a plugin's name

---

plugin.js
test/await-after.test.js
test/fixtures/dummy.txt

This PR proposes a fix for the plugin registration race condition we're seeing in this `fastify` issue :
https://github.com/fastify/fastify/issues/3726
The TL;DR; is that it appears the use of a top-level `await` between some (but not all) plugin registrations can get `avvio`'s root plugin into a weird state where it resolves an `after()` promise prior to in-flight registration functions having completed.  The issue doesn't occur if a top-level `await` statement exists between either ALL plugins or NONE of them.
I compared the `DEBUG=avvio` output between a "bad" boot sequence (e.g., what's in the [sample repo](https://github.com/chrskrchr/fastify-plugin-race-condition))  and "good" boot sequence …

fix: delay plugin promise resolution until next tick

---

test/await-after.test.js
test/express.test.js

Just some changes for test cases while I run `npm run test` in my env.
for `express.test.js`, makes port random, `3000` is easy to be Occupied
for `awat-after.test.js`, add a case with `after` callback function, and use `record` param to record the execution order

test: change test case for avvio

---

plugin.js
test/await-after.test.js
test/await-use.test.js
test/fixtures/dummy.txt

This PR is a followup to #173.  That original PR attempted to fix the async plugin loading issue described in [fastify/3726](https://github.com/fastify/fastify/issues/3726) by delaying each plugin's `after` promise resolution until the next tick.  However, this resulted in a subtle but significant change where subsequent plugin registration functions were now being enqueued in `this.q` and executed on the same tick of the event loop as registration, a consequence of the registration function being the only item in `this.q`.  We observed a symptom of this change in the unrelated unit test linked below:
https://github.com/fastify/avvio/pull/173/files#r814200533
We didn't think the above was a …

fix: delay plugin loading until next tick

---

boot.js
test/await-use.test.js
test/chainable.test.js

Signed-off-by: Matteo Collina <hello@matteocollina.com>
Fixes: https://github.com/fastify/fastify/issues/4125

Make sure we always start in a microtick

---

README.md
test/async-await.test.js
test/override.test.js

use isPrototypeOf from Object.prototype

---

boot.js

fix codesmell in callWithCbOrNextTick and closeWithCbOrNextTick

---

lib/errors.js

synchronize with fastify-errors

---

boot.js
test/async-await.test.js

Fixed crash when error is thrown in ready queue when timeout is 0

Fixed error in queue when timeout is 0

---

lib/errors.js
test/errors.test.js

Hi there,
I believe there is a typo. This PR fixes it.
By making a contribution to this project, I certify that:
* (a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
* (b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or
* (c) The contribution was provided directly to me by some other
person who certified (a), (b) or (c) and I have not modified
it.
* (d) I understand …

Fix error code of AVV_ERR_ROOT_PLG_BOOTED

---

package.json
test/async-await.test.js

Why use a package if we can use native promises and it is basically a three liner.

remove then-sleep dev dependency

---

package.json
test/esm.test.js

We needed semver to skip a test if the node instance was lower than 13.3.0. We support 14 and above. So no need to skip and no need for semver.

remove semver as dev dependency

---

lib/get-plugin-name.js
plugin.js
test/lib/get-plugin-name.test.js

extract getPluginName

---

lib/errors.js
package.json
test/errors.test.js

alternative to #197 
@mcollina asked if we can use @fastify/error directly. This PR uses @fastify/error instead of AVVIO own implementation. Only difference is, that the name of the Errors will be FastifyError instead of AvvioError.

use @fastify/error

---

boot.js
lib/time-tree.js
test/lib/time-tree.test.js

Based on #218 I assume that we should use null as initializiation value for stop. 
Also making named export for TimeTree to keep the style we use in the new files ;)

use named export for timeTree, use null as initialization value for TimeTreeNode.stop

---

boot.js
lib/load-plugin.js
plugin.js
test/lib/load-plugin.test.js

I modified it, by passing the instance as a parameter instead of binding. 
If you are against this change, I can change it to use again bind and this. 

extract loadPlugin

---

boot.js
lib/is-promise-like.js
lib/load-plugin.js
plugin.js
test/lib/is-promise-like.test.js

add isPromiseLike

---

lib/create-promise.js
lib/is-bundled-or-typescript-plugin.js
lib/validate-plugin.js

While working with jsdoc checking with typescript, I realized the jsdoc typings have issues. So I fixed them here.
Also renamed the parameter names to maybeX in the typeguards

improve jsdoc and parameter names

---

plugin.js

I could not find any use of this attribute. Also fastq doesnt use it. So maybe it is some artifact. 

remove unused onFinish attribute of Plugin

---

boot.js
test/basic.test.js

This PR fixes an issue, where calling avvio with new would result in a broken result, as enriching the instance with the avvio attributes would only happen if we didnt call it with new. 

fix: calling avvio with new

---

boot.js
lib/executeWithThenable.js
lib/thenify.js
test/lib/executeWithThenable.test.js
test/lib/thenify.test.js

based on #199 by @climba03003 

chore: extract thenify and executeWithThenable

---

boot.js
lib/errors.js
test/chainable.test.js
test/errors.test.js
test/expose.test.js

Make wrap() function a method `_expose()`

chore: move wrap to be method _expose()

---

README.md
boot.js
test/gh-issues/bug-205.test.js
test/plugin-name.test.js
test/pretty-print.test.js
test/to-json.test.js

Simplify the code, add a _trackPluginLoading and also fix the root name. It will now show root and not "bound root". Which is nicer imho.

chore: add _trackPluginLoading method and fix root name

---

boot.js

We dont need this attribute, when we can refer to the symbol directly

chore: remove _isOnCloseHandlerKey

---

lib/time-tree.js
test/lib/time-tree.test.js
test/plugin-loaded-so-far.test.js

@Eomm 
@mcollina 
What is the point of loadedSoFar? It seems that it basically always resolves immediatly, even though the plugin is not loaded fully. Totally confusing. See failing unit test

loadedSoFar, add unit tests

---

README.md
boot.js
lib/debug.js
lib/plugin.js
test/await-after.test.js
test/await-use.test.js
test/express.test.js

See https://github.com/fastify/fastify-static/pull/407

perf: use `node:` prefix to bypass require.cache call for builtins

---

index.d.ts
test/types/index.ts

This change correct the type of `options` argument of the `use` function following this line of code https://github.com/fastify/avvio/blob/4f2e04b3be362c1f77e5b50abc2fbd987565dd44/lib/plugin.js#L77
Note: tests on my local machine returns a lot of errors but I didn't get the problem, hope it's work in CI

Fix: use options as function type

---

package.json

@mcollina 
When you published v8.3.0 you accidently added debug and archy as dependencies.

chore: remove unused deps

---

boot.js
lib/plugin.js
test/plugin-timeout.test.js

Fixes https://github.com/fastify/fastify/issues/5410

Do not crash if nested plugin does not call next

---

boot.js
test/plugin-timeout-await.test.js

This PR changes avvio to make the error message indicate the correct plugin that timed out.

Fix timeout count for nested plugins

---

index.d.ts
test/types/index.ts

This PR correct the "expose" config typing by adding "close" and  "onClose" options

Fix typings for expose "close" and  "onClose" 

---

boot.js
test/on-ready-timeout-await.test.js

I don't really know if it is the right approach neither how to do a proper test case yet. Please advise :)
The main use case is to get a proper name in fastify instead of `bound _encapsulateThreeParam`: 
```
ERROR (32467): Uncaught Exception: A callback for 'onReady' hook timed out. You may have forgotten to call 'done' function or to resolve a Promise
err: {
"type": "FastifyError",
"message": "A callback for 'onReady' hook timed out. You may have forgotten to call 'done' function or to resolve a Promise: Plugin did not start in time: 'bound _encapsulateThreeParam'. You may have forgotten to call 'done' function or to resolve a Promise",
"stack":
FastifyError: A callback for 'onReady' hook timed out. You may have forgotten to call 'done' function or to resolve a Promise
```
and the [Code …

Get original function name in AVV_ERR_READY_TIMEOUT

---

index.d.ts
test/types/index.ts

Updated `avvio.Options` typings to include the (optional) `timeout` field, documented [here](https://github.com/fastify/avvio?tab=readme-ov-file#avvioinstance-options-started).

fix: expose timeout typing

---

index.d.ts
test/types/index.ts

backport: https://github.com/fastify/avvio/pull/263 in current release line before shipping a new patch (few commits are not released)

fix(type): expose timeout typing (#263)

---

README.md
eslint.config.js
index.d.ts
package.json
test/types/index.ts

See https://github.com/fastify/fastify-cors/pull/340. This is a batch PR, so may have some issues. Please review changes.

build(deps-dev): replace standard with neostandard
